apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-data-admin-statefulset-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-disk # Specify the name of your chosen StorageClass
  resources:
    requests:
      storage: 1Gi
