name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and execute command
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.131.141.214 << 'EOF' #replace IP or domain , if changed 
            cd /var/www/html/lms_leopard
            echo "yes started updating"

            # Grant necessary permissions
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .

            # Ensure the storage and bootstrap/cache directories and their contents are writable by the web server user 
            sudo chown -R www-data:www-data /var/www/html/lms_leopard/storage
            sudo chown -R www-data:www-data /var/www/html/lms_leopard/bootstrap/cache

            #Ensure that the directories have the correct permissions to allow writing.
            sudo chmod -R 775 /var/www/html/lms_leopard/storage
            sudo chmod -R 775 /var/www/html/lms_leopard/bootstrap/cache

            #restart server after applying permissions
            sudo systemctl restart apache2

            #ls
            
            # Reset local changes and pull latest from remote
            git reset --hard HEAD
            git pull origin main

            echo "done deployment"
            # Add any additional deployment commands here
          EOF
